baseURL = "/"
languageCode = "en-us"
title = "NGINX Documentation"
refLinksErrorLevel = "WARNING"

[caches]
  [caches.modules]
    maxAge = -1

[[module.imports]]
  path="github.com/nginxinc/nginx-hugo-theme"

[params]
  useSectionPageLists = "false"
  buildtype = "webdocs"
  RSSLink = "/index.xml"
  author = "NGINX Inc." # add your company name
  github = "nginxinc" # add your github profile name
  twitter = "@nginx" # add your twitter profile
  #email = ""
  noindex_kinds = [
    "taxonomy",
    "taxonomyTerm"
  ]
  taxonomiesExcludedFromSitemap = ["tags", "categories", "doctypes"]
  logo = "NGINX-Management-Suite-product-icon.svg"
  nimvers = [ # list of NIM versions for the versions shortcode
    "0.9",
    "1.0",
    "2.0.0",
    "2.0.1",
    "2.1.0",
    "2.2.0",
    "2.3.0",
    "2.4.0",
    "2.5.0",
    "2.6.0",
    "2.7.0",
    "2.8.0",
    "2.9.0",
  ]
  acmvers = [ # list of ACM versions for the shortcode
    "1.0.0",
    "1.1.0",
    "1.1.1",
    "1.2.0",
    "1.3.0",
    "1.3.1",
    "1.4.0",
    "1.4.1",
    "1.5.0"
  ]

  secvers = [ # list of Security Monitoring versions for the shortcode
    "1.0.0",
    "1.1.0",
    "1.2.0",
    "1.3.0"
  ]

sectionPagesMenu = "docs"

ignoreFiles = [ "\\.sh$", "\\.DS_Store$", "\\.git.*$", "\\.txt$", "\\/config\\/.*", "README\\.*"]
