baseURL = "/"
languageCode = "en-us"
title = "NGINX Documentation"
refLinksErrorLevel = "WARNING"

[caches]
  [caches.modules]
    maxAge = -1

[[module.imports]]
  path="github.com/nginxinc/nginx-hugo-theme"

