baseURL = "/"
languageCode = "en-us"
title = "NGINX Documentation"
refLinksErrorLevel = "ERROR"

[caches]
  [caches.modules]
    maxAge = -1

[[module.imports]]
  path="github.com/nginxinc/nginx-hugo-theme"

[params]
  useSectionPageLists = "false"
  buildtype = "webdocs"
  RSSLink = "/index.xml"
  author = "NGINX Inc." # add your company name
  github = "nginxinc" # add your github profile name
  twitter = "@nginx" # add your twitter profile
  #email = ""
  noindex_kinds = [
    "taxonomy",
    "taxonomyTerm"
  ]
  taxonomiesExcludedFromSitemap = ["tags", "categories", "doctypes"]
  
  #logo = "NGINX-Management-Suite-product-icon.svg"

  # Version lists; used by the versions shortcode
  nimvers = [ # list of NIM versions for the versions shortcode
    "0.9",
    "1.0",
    "2.0.0",
    "2.0.1",
    "2.1.0",
    "2.2.0",
    "2.3.0",
    "2.4.0",
    "2.5.0",
    "2.6.0",
    "2.7.0",
    "2.8.0",
    "2.9.0",
  ]
  acmvers = [ # list of ACM versions for the shortcode
    "1.0.0",
    "1.1.0",
    "1.1.1",
    "1.2.0",
    "1.3.0",
    "1.3.1",
    "1.4.0",
    "1.4.1",
    "1.5.0"
  ]

  secvers = [ # list of Security Monitoring versions for the shortcode
    "1.0.0",
    "1.1.0",
    "1.2.0",
    "1.3.0"
  ]

  ctrlvers = [ # list of controller versions for the versions shortcode
    "3.0",
    "3.1",
    "3.2",
    "3.3",
    "3.3",
    "3.4",
    "3.5",
    "3.6",
    "3.7",
    "3.8",
    "3.9",
    "3.10",
    "3.12",
    "3.13",
    "3.14",
    "3.15",
    "3.16.1",
    "3.17",
    "3.18",
    "3.18.1",
    "3.18.2",
    "3.18.3"
  ]

  apimvers = [ # list of Cv3 APIM versions for the versions shortcode
    "3.18",
    "3.18.1",
    "3.19",
    "3.19.1",
    "3.19.2",
    "3.19.3",
    "3.19.4",
    "3.19.5"
  ]

  adcvers = [ # list of Cv3 ADC versions for the versions shortcode
    "3.20",
    "3.20.1",
    "3.21",
    "3.22",
    "3.22.1",
    "3.22.2",
    "3.22.3",
    "3.22.4",
    "3.22.5",
    "3.22.6",
    "3.22.7",
    "3.22.8"
  ]

sectionPagesMenu = "docs"

ignoreFiles = [ "\\.sh$", "\\.DS_Store$", "\\.git.*$", "\\.txt$", "\\/config\\/.*", "README\\.*"]
