{
 "title": "NGINX Service Mesh Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>Global View</span>\n</div>"
   }
  },
  {
   "title": "Global Sucess Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(nginxplus_upstream_server_responses{code=~\"1xx|2xx\"}[30s])) / sum(irate(nginxplus_upstream_server_responses[30s]))"
    }
   ]
  },
  {
   "title": "Pods Monitored",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nginxplus_http_requests_total)"
    }
   ]
  },
  {
   "title": "Global Request Volume",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(nginxplus_http_requests_total[30s]))"
    }
   ]
  },
  { "title": "Workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<div class=\"dashboard-header text-center\">\n<span>Workload View</span>\n</div>"
   }
  },
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(nginxplus_http_requests_total[30s])",
     "legendFormat": "App: {{app}} Ver: {{version}} NS: {{namespace}}"
    }
   ]
  },
  {
   "title": "Pod Success",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginxplus_upstream_server_responses{code=~\"1xx|2xx\"}[30s])) by (app, version) / sum(irate(nginxplus_upstream_server_responses[30s])) by (app, version)",
     "legendFormat": "App: {{app}} Ver: {{version}}"
    }
   ]
  }
 ]
}