# markdownlint enables all rules by default
# Setting default to false means that rules are
# instead enabled on a case-by-case basis
default: false

# Heading levels should only increment by one level at a time
MD001: true

# Detects if link brackets are in the wrong order: ()[]
MD011: true

# No multiple consecutive blank lines
MD012: true

# Headings should be surrounded by blank lines
MD022: true

# Headings must start at the beginning of a line
MD023: true

# No trailing punctuation in headings
MD026: true

# Code blocks should be surrounded by blank lines
MD031: true

# Lists should be surrounded by blank lines
MD032: true

# Emphasis should not be used instead of headings
MD036: true

# No spaces on the outside of link text
MD039: true

# All images should have alt text
MD045: true

# Tables shou ld be surrounded by blank lines
MD058: true