default: true

MD002: false
MD013:
  line_length: 300
  heading_line_length: 60
  code_block_line_length: 80
  code_blocks: true
  tables: true
  headings: true
  headers: true
  strict: false
  stern: false