[build]
  publish = "public"

[context.production]
  command = "make all"  
  publish = "public"
  
[context.staging]
  command = "make all-staging"
  publish = "public"

[context.development]
  command = "make all-dev"
  publish = "public"

[context.deploy-preview]
  command = "make deploy-preview"
  publish = "public"

[context.branch-deploy]
  command = "make deploy-preview"
  publish = "public"

[[redirects]]
  from = "/nginx-management-suite/"
  to = "/nms/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404