[build]
  publish = "public"

[context.production]
  # keep while docs-dev is the production site
  # this will change to make all when we go live on production site 
  command = "./build.sh"  
  publish = "public"
  
#[context.staging]
#  command = "make all-staging"
#  publish = "public"

#[context.dev]
#  command = "make all-dev"
#  publish = "public"

[context.deploy-preview]
  command = "make deploy-preview"
  publish = "public"

[context.branch-deploy]
  command = "make deploy-preview"
  publish = "public"

# Product path rewrites
#[[redirects]]
#  from = "/nginx-app-protect-dos/*"
#  to = "/nap-dos/:splat"
#  force = true
#  status = 200

#[[redirects]]
#  from = "/nginx-app-protect-waf/*"
#  to = "/nap-waf/:splat" 
#  force = true
#  status = 200

#[[redirects]]
#  from = "/nginx-controller/*"
#  to = "/controller/:splat"
#  force = true
#  status = 200

#[[redirects]]
#  from = "/nginx-management-suite/*"
#  to = "/nms/:splat"
#  force = true
#  status = 200

#[[redirects]]
#  from = "/nginx-waf/*"
#  to = "/modsec-waf/:splat"
#  force = true
#  status = 200

# Keep the 404 redirect defined here
# Netlify processes the _redirects file first
# This rule should always be processed last
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404