[build]
  publish = "public"

[context.production]
  # The production command runs the build.sh script
  # This ensures the build uses the correct baseURL
  # for the site being built
  command = "./build.sh"  
  publish = "public"

[context.deploy-preview]
  command = "make deploy-preview"
  publish = "public"
  NGINX_THEME_VERSION = "0.40.2-beta"

[context.branch-deploy]
  command = "make deploy-preview"
  publish = "public"
  NGINX_THEME_VERSION = "0.40.2-beta"

# Keep the 404 redirect defined here
# Netlify processes the _redirects file first
# This rule should always be processed last
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[functions."coveo"]
  schedule = "@daily"