{
 "title": "NGINX Mesh Top",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GLOBAL SUCCESS RATE",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(nginxplus_upstream_server_responses{code=~\"1xx|2xx\"}[30s])) / sum(irate(nginxplus_upstream_server_responses[30s]))"
    }
   ]
  },
  {
   "title": "GLOBAL REQUEST VOLUME",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 13, "x": 8, "y": 0 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(nginxplus_http_requests_total[30s]))"
    }
   ]
  },
  {
   "title": "PODS MONITORED",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nginxplus_http_requests_total)"
    }
   ]
  },
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(nginxplus_http_requests_total[30s])"
    }
   ]
  },
  {
   "title": "Pod Success",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(nginxplus_upstream_server_responses{code=~\"1xx|2xx\"}[30s])) by (app, version) / sum(irate(nginxplus_upstream_server_responses[30s])) by (app, version)"
    }
   ]
  },
  {
   "title": "Sidecar Memory Usage (RSS)",
   "type": "graph",
   "description": "RSS used by NGINX Service Mesh sidecars",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nginxplus_workers_mem_rss" }
   ]
  },
  {
   "title": "Sidecar Memory Usage (Private)",
   "type": "graph",
   "description": "Private memory used by NGINX Service Mesh sidecars",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginxplus_workers_mem_private" }
   ]
  }
 ]
}