openapi: 3.0.3
servers:
  - url: /api/v1
info:
  title: Manage NGINX Instances
  description: |
    Manage your NGINX dataplane instances, view security advisories (CVEs), and analyze NGINX configurations for issues and recommendations.
  version: "v1"
tags:
  - name: "Instances"
paths:
  /instances/summary:
    get:
      tags:
        - "Instances"
      summary: List summary details for all instances
      description: |
        Returns summarized information for all NGINX instances, including:
          * Certificates and associations
          * Operating system
          * NGINX Agent version
          * System status
      operationId: listSummary
      responses:
        '200':
          description: The summary details for all NGINX instances were successfully returned.
          content:
            application/json:
              schema:
                $ref: "../../common.yaml#/components/schemas/InstanceSummary"
  /instances:
    get:
      tags:
        - "Instances"
      summary: List all instances
      operationId: listInstances
      description: |
        Returns a list of all NGINX instances, including:
          * Unique identifiers
          * Timestamps of key actions (registration, last reported, etc.)
          * NGINX build data
          * Agent version
      parameters:
        - $ref: '../../common.yaml#/components/parameters/Paginated'
        - $ref: '../../common.yaml#/components/parameters/Limit'
        - $ref: '../../common.yaml#/components/parameters/Offset'
        - $ref: '../../common.yaml#/components/parameters/FilterFieldInstances'
        - $ref: '../../common.yaml#/components/parameters/FilterOperands'
        - $ref: '../../common.yaml#/components/parameters/FilterValues'
      responses:
        '200':
          description: The list of NGINX instances was successfully returned.
          content:
            application/json:
              schema:
                $ref: "../../common.yaml#/components/schemas/InstanceListResponse"
  /instances/{instanceUUID}/cves:
    get:
      tags:
        - "Instances"
      summary: Retrieve an instance's security advisories (CVEs)
      description: Retrieves a list of the security advisories (CVEs) for an NGINX instance.
      operationId: listSecurityAdvisories
      parameters:
        - $ref: '../../common.yaml#/components/parameters/InstanceUUID'
      responses:
        '404':
          description: An NGINX instance could found for the specified UUID.
        '200':
          description: The security advisories for the NGINX instance were successfully returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "../../common.yaml#/components/schemas/NginxSecurityAdvisory"

  /instances/{instanceUUID}:
    get:
      tags:
        - "Instances"
      summary: Retrieve an instance
      description: |
        Retrieve the details for an NGINX instance, including
        * Hostname
        * System status
        * Timestamps of key actions (registration, last reported, etc.)
        * NGINX build information
        * Certificate data
        * Operating system version
        * NGINX Agent version
        
      operationId: getInstance
      parameters:
        - $ref: '../../common.yaml#/components/parameters/InstanceUUID'
      responses:
        '404':
          description: An NGINX instance could not found for the specified UUID.
        '200':
          description: The NGINX instance was successfully returned.
          content:
            application/json:
              schema:
                $ref: "../../common.yaml#/components/schemas/InstanceDetails"

    delete:
      tags:
        - "Instances"
      summary: Delete an instance
      description: |
        Deletes an NGINX instance. Associations with certificates will be cleaned up.

      operationId: deleteInstance
      parameters:
        - $ref: '../../common.yaml#/components/parameters/InstanceUUID'
      responses:
        '404':
          description: An NGINX instance could not be found for the specified UUID.
        '204':
          description: The NGINX instance was successfully deleted.

  /instances/{instanceUUID}/config-report:
    get:
      tags:
        - "Instances"
      summary: Analyze an instance's NGINX configuration
      description: |
        Analyzes the configuration of an NGINX instance and returns a detailed report.
        The report includes insights, identified issues, and recommendations for optimizing and troubleshooting.
      operationId: getConfigReport
      parameters:
        - $ref: '../../common.yaml#/components/parameters/InstanceUUID'
      responses:
        '404':
          description: An NGINX instance could not found for the specified UUID.
        '200':
          description: The NGINX configuration analysis report was successfully returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "../../common.yaml#/components/schemas/NginxConfigReport"

  /instances/{instanceUUID}/config:
    get:
      tags:
        - "Instances"
      summary: Retrieve an instance's configuration details
      description: |
        Returns the configuration details for an NGINX instance, including: 
        * Main configuration path
        * Details about configuration files
        * Details about auxiliary files
        * Unique identifiers
      operationId: getInstanceConfig
      parameters:
        - $ref: '../../common.yaml#/components/parameters/InstanceUUID'
      responses:
        '404':
          description: An NGINX instance could not be found for the specified UUID.
        '200':
          description: The instance's configuration details were successfully returned.
          content:
            application/json:
              schema:
                $ref: "../../common.yaml#/components/schemas/NginxConfig"
