{
 "title": "NGINX Landscape",
 "description": "NGINX Instance Manager landscape",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(hostname)" } },
   {
    "name": "uuid",
    "query": {
     "query": "label_values({hostname=\"$hostname\"},uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "{__name__=\"system_mem_pct_used\",hostname=\"$hostname\"}",
     "legendFormat": "% memory used"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100-system_cpu_idle{hostname=\"$hostname\"}",
     "legendFormat": "CPU pct"
    }
   ]
  },
  {
   "title": "Swap Free %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "system_swap_pct.free{hostname=\"$hostname\"}",
     "legendFormat": "Swap used"
    }
   ]
  },
  {
   "title": "Load %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100*system_load_avg5{hostname=\"$hostname\"}",
     "legendFormat": "Load %"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{subsystem=\"load\",hostname=\"$hostname\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{subsystem=\"cpu\",hostname=\"$hostname\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{subsystem=\"mem\",__name__!=\"system_mem_pct_used\",hostname=\"$hostname\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{subsystem=\"swap\",hostname=\"$hostname\",__name__!=\"system_swap_pct.free\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "2xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(nginx_http_responses_2xx_count{uuid=\"$uuid\",plus_zone!~\".+\"})[300s]",
     "legendFormat": "$hostname count"
    },
    {
     "expr": "nginx_http_responses_2xx_count{uuid=\"$uuid\",plus_zone=~\".+\"}[300s]",
     "legendFormat": "{{plus_zone}}"
    }
   ]
  },
  {
   "title": "3xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(nginx_http_responses_3xx_count{uuid=\"$uuid\",plus_zone!~\".+\"})[300s]",
     "legendFormat": "$hostname count"
    },
    {
     "expr": "nginx_http_responses_3xx_count{uuid=\"$uuid\",plus_zone=~\".+\"}[300s]",
     "legendFormat": "{{plus_zone}}"
    }
   ]
  },
  {
   "title": "4xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(nginx_http_responses_4xx_count{uuid=\"$uuid\",plus_zone!~\".+\"})[300s]",
     "legendFormat": "$hostname count"
    },
    {
     "expr": "nginx_http_responses_4xx_count{uuid=\"$uuid\",plus_zone=~\".+\"}[300s]",
     "legendFormat": "{{plus_zone}}"
    }
   ]
  },
  {
   "title": "5xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(nginx_http_responses_5xx_count{uuid=\"$uuid\",plus_zone!~\".+\"})[300s]",
     "legendFormat": "$hostname count"
    },
    {
     "expr": "nginx_http_responses_5xx_count{uuid=\"$uuid\",plus_zone=~\".+\"}[300s]",
     "legendFormat": "{{plus_zone}}"
    }
   ]
  }
 ]
}