name: Build and deploy (docs)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - dev
          - staging
          - prod
      hugo_theme_override:
        description: "Override hugo theme (leave blank to use latest version)"
        required: false
        default: ""
        type: string
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "staging"

jobs:
  call-docs-build-push:
    uses: nginxinc/docs-actions/.github/workflows/docs-build-push.yml@69843fb5d009e99750e50c23e90c23a899e4637e # v1.0.6
    with:
      production_url_path: ""
      preview_url_path: "/previews/docs"
      docs_source_path: "public"
      docs_build_path: "./"
      doc_type: "hugo"
      environment: ${{inputs.environment}}
      force_hugo_theme_version: ${{inputs.hugo_theme_override}}
      auto_deploy_branch: "staging"
      auto_deploy_env: "staging"
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS}}
      AZURE_KEY_VAULT: ${{secrets.AZURE_KEY_VAULT}}
