name: Build and deploy (docs)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "preview"
        type: choice
        options:
          - preview
          - dev
          - staging
          - prod
      hugo_theme_override:
        description: "Override hugo theme (leave blank to use latest version)"
        required: false
        default: ""
        type: string
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "nim-release-2.18.0"

jobs:
  prod-check-branch:
    runs-on: ubuntu-24.04
    steps:
      - name: Output variables
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Branch: ${{ github.ref }}"
      - name: Checks to see that main branch is selected if deploying to prod
        if: ${{ inputs.environment == 'prod' && github.ref != 'refs/heads/main' }}
        run: |
          echo "Deployment to 'prod' can only be done from the 'main' branch."
          exit 1

  call-docs-build-push:
    needs: prod-check-branch
    uses: nginxinc/docs-actions/.github/workflows/docs-build-push.yml@9c59fab05a8131f4d691ba6ea2b6a119f3ef832a # v1.0.7
    with:
      production_url_path: ""
      preview_url_path: "/previews/docs"
      docs_source_path: "public"
      docs_build_path: "./"
      doc_type: "hugo"
      environment: ${{inputs.environment}}
      force_hugo_theme_version: ${{inputs.hugo_theme_override}}
      auto_deploy_branch: "nim-release-2.18.0"
      auto_deploy_env: "staging"
    secrets:
      AZURE_CREDENTIALS: ${{secrets.AZURE_CREDENTIALS_DOCS}}
      AZURE_KEY_VAULT: ${{secrets.AZURE_KEY_VAULT_DOCS}}
