name: Detect changes in documentation within nginx/nginx.org

on:
  schedule:
    - cron: "0 */23 * * *"
permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:      
  detect-changes:
    name: Detect changes in 'en' docs of nginx/nginx.org
    runs-on: ubuntu-latest
    outputs:
      IS_CHANGES_DETECTED: ${{ steps.check_changes.outputs.changed }}
    steps: 
      - name: Checkout Repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.2
        with:
          fetch-depth: 0
      - name: Clone the nginx/nginx-org repository
        run: |
            git clone --depth=2 https://github.com/nginx/nginx.org.git dot-org-repo
      - name: Check for changes in xml/en folder
        id: check_changes
        run: |
            cd dot-org-repo

            if git whatchanged --since="1 day ago" -- _xml/en/; then
              echo "Changes detected in /en"
              echo "changed=true" >> $GITHUB_OUTPUT
            else
              echo "No changes in /en"
              echo "changed=false" >> $GITHUB_OUTPUT
            fi
      - name: Execute make target 'make hugo-md' to generate markdown
        if: steps.check_changes.outputs.changed == 'true'
        run: |
            cd dot-org-repo
            make module-markdown
      - name: Create PR 
        uses: peter-evans/create-pull-request@v7
        if: steps.check_changes.outputs.changed == 'true'
        with:
          commit-message: "chore: Update nginx plus module reference from detected changes in nginx/nginx.org"
          labels: product/nginx-plus, dependencies, module-reference
          base: main
          branch: update-nginx-module-ref
          title: 'NGINX Plus - Module Ref: Update content for content/nginx due to detected changes'
          add-paths: |
            dot-org-repo/libxslt-md/
            dot-org-repo/yaml/nginx_api.yaml
          body: |
            ### Proposed Changes
            Updated NGINX Plus docs.
