name: PR Labeler

on:
- pull_request_target

permissions:
  contents: read  # Required to read the labeler.yml file
  pull-requests: write  # Required to apply labels to PRs

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels based on file paths
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
